name: Release

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      version:
        type: string
        default: ""
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - run: |
          go test -race -cover ./...
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - id: build 
        run: |
          MATRIX=("linux/amd64" "linux/arm64" "darwin/arm64" "windows/amd64")
          mkdir dist

          VERSION=${INPUT_VERSION:-${GITHUB_REF}}
          echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}

          for platform in ${MATRIX[@]}; do
            goos=$(cut -d '/' -f1 <<< $platform)
            goarch=$(cut -d '/' -f2 <<< $platform)
            ext=""
            [[ $goos == "windows" ]] && ext=".exe"

            GOOS=$goos GOARCH=$goarch CGO_ENABLED=0 go build -o dist/semver_${goos}_${goarch}_${VERSION}${ext} -trimpath -ldflags="-s -w -X 'main.version=${VERSION}' -X 'main.buildRef=${GITHUB_SHA:0:7}'" ./semver-cli/
          done
        env:
          INPUT_VERSION: ${{inputs.version}}
      - uses: actions/upload-artifact@v7
        env:
          VERSION: ${{steps.build.outputs.VERSION}}
        with:
          name: binaries
          path: |
              dist/semver_linux_amd64_${VERSION}
              dist/semver_linux_arm64_${VERSION}
              dist/semver_darwin_arm64_${VERSION}
              dist/semver_windows_amd64_${VERSION}.exe
  upload-release-assets:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        id: download-artifacts
        with:
          name: binaries
      - run: |
          VERSION=${INPUT_VERSION:-${GITHUB_REF}}
          ls -R $DOWNLOAD_DIR
        env:
          INPUT_VERSION: ${{inputs.version}}
          DOWNLOAD_DIR: ${{steps.download-artifacts.outputs.download-path}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
