name: "Continuous Integration"

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run Tests
        run: |
          GO_VERSION=$(awk '/^go / {print $NF}' go.mod)
          echo "go version ${GO_VERSION}"
          GOTOOLCHAIN="go${GO_VERSION}+auto" go test -race -cover ./...
      - name: Build
        run: go build -o $TMPDIR/semver-cli ./semver-cli/
