name: "Continuous Integration"

on:
  push:
    branches: [main]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        go: [oldstable, stable]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        id: setup-go
        with:
          go-version: ${{matrix.go}}
      - name: Run Tests
        env:
          GOOS: linux
          GOARCH: ${{matrix.arch}}
          GOVERSION: ${{steps.setup-go.outputs.go-version}}
        run: |
          GOTOOLCHAIN="go${GOVERSION}+auto"

          echo "using go version ${GOVERSION} with toolchain ${GOTOOLCHAIN}"
          export GOTOOLCHAIN

          go test -race -cover ./...
      - name: Build
        env:
          GOOS: linux
          GOARCH: ${{matrix.arch}}
        run: go build -o $(mktemp) ./semver-cli/
