name: "Continuous Integration"

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run Tests
        run: go test -race -cover ./...
      - name: Build
        run: go build -o $TMPDIR/cli ./cli/
